export const CART_STATE_REQUEST = 'CART_STATE_REQUEST';
export const CART_STATE_SUCCESS = 'CART_STATE_SUCCESS';
export const CART_STATE_FAIL = 'CART_STATE_FAIL';

export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';

export const CART_RESET = 'CART_RESET';
