export const ORDER_CHECKOUT_SET_ITEMS = 'ORDER_CHECKOUT_SET_ITEMS';
export const ORDER_CHECKOUT_SAVE_SHIPPING_ADDRESS = 'ORDER_CHECKOUT_SAVE_SHIPPING_ADDRESS';
export const ORDER_CHECKOUT_SAVE_PAYMENT_METHOD = 'ORDER_CHECKOUT_SAVE_PAYMENT_METHOD';
export const ORDER_CHECKOUT_RESET = 'ORDER_CHECKOUT_RESET';

export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST';
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS';
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL';
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET';

// --- ADD THESE MISSING LINES ---
export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';
export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST';
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS';
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL';
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET';
// --- END OF FIX ---
export const ORDER_RETURN_REQUEST_REQUEST = 'ORDER_RETURN_REQUEST_REQUEST';
export const ORDER_RETURN_REQUEST_SUCCESS = 'ORDER_RETURN_REQUEST_SUCCESS';
export const ORDER_RETURN_REQUEST_FAIL = 'ORDER_RETURN_REQUEST_FAIL';
export const ORDER_RETURN_REQUEST_RESET = 'ORDER_RETURN_REQUEST_RESET';

export const RETURN_LIST_MY_REQUEST = 'RETURN_LIST_MY_REQUEST';
export const RETURN_LIST_MY_SUCCESS = 'RETURN_LIST_MY_SUCCESS';
export const RETURN_LIST_MY_FAIL = 'RETURN_LIST_MY_FAIL';

